name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install system deps
      run: sudo apt-get install -y libasound2-dev libxdo-dev
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -Dclippy::all
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
